/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/peft/tuners/tuners_utils.py:456: SyntaxWarning: invalid escape sequence '\.'
  layer_index = re.match(f".*.{pattern}\.(\d+)\.*", key)
/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/peft/tuners/lora/model.py:146: SyntaxWarning: invalid escape sequence '\.'
  target_name_key = next(filter(lambda key: re.match(f".*\.{key}$", current_key), pattern_keys), current_key)
/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/peft/tuners/lycoris_utils.py:230: SyntaxWarning: invalid escape sequence '\.'
  target_name_key = next(filter(lambda key: re.match(f"(.*\.)?{key}$", current_key), pattern_keys), target_name)
/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/wandb/analytics/sentry.py:90: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
  self.hub = sentry_sdk.Hub(client)
Traceback (most recent call last):
  File "/nfs-share/pa511/llm_memorisation/finetune/train_fl.py", line 55, in <module>
    , data_files=cfg.dataset.files # TODO: there is no such argument in my Federated Dataset class
                 ^^^^^^^^^^^^^^^^^
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/llm-memorization-iHoaSaFW-py3.12/lib/python3.12/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key files
    full_key: dataset.files
    object_type=dict
srun: error: mauao: task 0: Exited with exit code 1
